{{- if .Values.knativeDeploy }}
{{- else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: merchant-config
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  merchant_db: "Hello World"