{{- if .Values.knativeDeploy }}
{{- else }}
apiVersion: v1
kind: ConfigMap
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  merchant_db: "Hello World"