{{- if .Values.knativeDeploy }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "fullname" . }}
{{- end }}
---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "merchant-db"
spec:
  type: ExternalName
  externalName: merchantservicedb.cwehwynauojy.us-east-1.rds.amazonaws.commerchantservicedb.cwehwynauojy.us-east-1.rds.amazonaws.com
selector: {}